#!/bin/bash

#can be run as curl https://raw.githubusercontent.com/kaywoz/gluestuff/main/linux/bashbits-install_tailscale | sudo bash

# download all tailscale bits
curl -fsSL https://tailscale.com/install.sh | sudo bash

#run tailscale
sudo tailscale up --authkey tskey-placeholder

#Note, device approval is in effect.