#!/bin/bash

#can be run as curl https://raw.githubusercontent.com/kaywoz/gluestuff/main/linux/bashbits-install_tailscale | sudo bash

# download all tailscale bits
curl -fsSL https://tailscale.com/install.sh | sudo tee /tmp/tailscale.sh > /dev/null
sudo chmod +x /tmp/tailscale.sh
sudo /tmp/tailscale.sh
sudo tailscale up --authkey PLACEHOLDEr
sudo rm /tmp/tailscale.sh
#run tailscale

#Note, device approval is in effect.